# US Census Demographic

In [1]:
# Import library 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Ingestion

### Data import from csv

In [2]:
# Import csv file to pandas dataframe

census_data = pd.read_csv('acs2015_census_tract_data.csv')
county_census_data = pd.read_csv('acs2015_county_data.csv')

In [3]:
### Display census data

census_data.head(10)

,CensusTract,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001020100,Alabama,Autauga,1948,940,1008,0.9,87.4,7.7,0.3,...,0.5,2.3,2.1,25.0,943,77.1,18.3,4.6,0.0,5.4
1,1001020200,Alabama,Autauga,2156,1059,1097,0.8,40.4,53.3,0.0,...,0.0,0.7,0.0,23.4,753,77.0,16.9,6.1,0.0,13.3
2,1001020300,Alabama,Autauga,2968,1364,1604,0.0,74.5,18.6,0.5,...,0.0,0.0,2.5,19.6,1373,64.1,23.6,12.3,0.0,6.2
3,1001020400,Alabama,Autauga,4423,2172,2251,10.5,82.8,3.7,1.6,...,0.0,2.6,1.6,25.3,1782,75.7,21.2,3.1,0.0,10.8
4,1001020500,Alabama,Autauga,10763,4922,5841,0.7,68.5,24.8,0.0,...,0.0,0.6,0.9,24.8,5037,67.1,27.6,5.3,0.0,4.2
5,1001020600,Alabama,Autauga,3851,1787,2064,13.1,72.9,11.9,0.0,...,0.0,6.0,4.5,19.8,1560,79.4,14.7,5.8,0.0,10.9
6,1001020700,Alabama,Autauga,2761,1210,1551,3.8,74.5,19.7,0.0,...,0.0,0.0,0.0,20.0,1166,82.0,14.6,3.4,0.0,11.4
7,1001020801,Alabama,Autauga,3187,1502,1685,1.3,84.0,10.7,3.1,...,0.0,1.7,5.9,24.3,1502,78.1,14.8,7.1,0.0,8.2
8,1001020802,Alabama,Autauga,10915,5486,5429,1.4,89.5,8.4,0.0,...,0.0,0.0,1.3,29.4,4348,73.3,22.1,4.6,0.0,8.7
9,1001020900,Alabama,Autauga,5668,2897,2771,0.4,85.5,12.1,0.0,...,0.0,1.2,2.1,32.9,2485,77.9,15.2,6.9,0.0,7.2

In [4]:
# Display county_census data
county_census_data.head()

,CensusId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga,55221,26745,28476,2.6,75.8,18.5,0.4,...,0.5,1.3,1.8,26.5,23986,73.6,20.9,5.5,0.0,7.6
1,1003,Alabama,Baldwin,195121,95314,99807,4.5,83.1,9.5,0.6,...,1.0,1.4,3.9,26.4,85953,81.5,12.3,5.8,0.4,7.5
2,1005,Alabama,Barbour,26932,14497,12435,4.6,46.2,46.7,0.2,...,1.8,1.5,1.6,24.1,8597,71.8,20.8,7.3,0.1,17.6
3,1007,Alabama,Bibb,22604,12073,10531,2.2,74.5,21.4,0.4,...,0.6,1.5,0.7,28.8,8294,76.8,16.1,6.7,0.4,8.3
4,1009,Alabama,Blount,57710,28512,29198,8.6,87.9,1.5,0.3,...,0.9,0.4,2.3,34.9,22189,82.0,13.5,4.2,0.4,7.7

In [11]:
# Display total number of rows and columns
print ("County census data contains {} row and {} columns" .format(county_census_data.shape[0],county_census_data.shape[1]))
print ("Census data contains {} row and {} columns" .format(census_data.shape[0],census_data.shape[1]))

County census data contains 3220 row and 37 columns
Census data contains 74001 row and 37 columns

In [14]:
#Display listof columns
county_census_data.columns

Index(['CensusId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'Citizen', 'Income',
       'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')